[package]
name = "n2"
version = "0.1.0"
edition = "2018"
# std::thread::available_parallelism
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
anyhow = "1.0"
libc = "0.2"
lazy_static = "1.4.0"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.48.0"
features = [
    "Win32_Storage_FileSystem",
    "Win32_System_Console",
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_System_Pipes",
    "Win32_Security"
]

[target.'cfg(not(windows))'.dependencies]
jemallocator = "0.3.2"

[dev-dependencies]
tempfile = "3.3.0"

[profile.release]
debug = true
